require 'database_cleaner'

DatabaseCleaner.clean_with(:truncation)

User.create(username: 'user', password: 'password')
User.create(username: 'user1', password: 'password')
User.create(username: 'user2', password: 'password')

EquipmentType.create(name: 'Mixer')
EquipmentType.create(name: 'Turntable')
EquipmentType.create(name: 'CDJ')
EquipmentType.create(name: 'Active Speaker')
EquipmentType.create(name: 'Subwoofer')

EquipmentModel.create(equipment_type_id: 1, name: 'Allen & Heath XONE: 96', description: '4 + 2 channel Analog Mixer', image:"https://cdn1.bigcommerce.com/server4700/d8d4f/product_images/uploaded_images/allen-and-heath-xone-96-dj-mixer-rental.-chicago.jpg" )
EquipmentModel.create(equipment_type_id: 1, name: 'Allen & Heath XONE: 92', description: '4 channel Analog Mixer', image: "https://cdn1.bigcommerce.com/server4700/d8d4f/product_images/uploaded_images/xone-92-rental.jpg")
EquipmentModel.create(equipment_type_id: 1, name: 'Pioneer DJM-900 Nexus', description: '4-channel Digital mixer', image: "https://cdn1.bigcommerce.com/server4700/d8d4f/product_images/uploaded_images/djm-900-nexus-rental.jpg")
EquipmentModel.create(equipment_type_id: 1, name: 'Pioneer DJM-900NXS2', description: '4-channel Digital mixer', image: "https://cdn1.bigcommerce.com/server4700/d8d4f/product_images/uploaded_images/djm-900nxs2-dj-mixer-rental.jpg")
EquipmentModel.create(equipment_type_id: 2, name: 'Technics SL-1200MK2', description: 'Turntable', image: "https://cdn1.bigcommerce.com/server4700/d8d4f/product_images/uploaded_images/technics-1200mk2-silver-rental.jpg")
EquipmentModel.create(equipment_type_id: 2, name: 'Pioneer PLX-1000', description: 'High-Torque Turntable', image: "https://cdn1.bigcommerce.com/server4700/d8d4f/product_images/uploaded_images/pioneer-dj-plx-1000-turntable-rental.jpg")
EquipmentModel.create(equipment_type_id: 3, name: 'CDJ-900 Nexus', description: 'CD & USB Stick Player', image: "https://cdn1.bigcommerce.com/server4700/d8d4f/product_images/uploaded_images/pioneer-cdj-900-nexus-rental.jpg")
EquipmentModel.create(equipment_type_id: 3, name: 'CDJ-2000 Nexus', description: 'Multi Player', image: "https://cdn1.bigcommerce.com/server4700/d8d4f/product_images/uploaded_images/cdj-2000-nexus-rental.jpg" )
EquipmentModel.create(equipment_type_id: 3, name: 'CDJ-2000NXS2', description: 'Multi Player High Res Audio', image: "https://cdn1.bigcommerce.com/server4700/d8d4f/product_images/uploaded_images/cdj-2000nxs2-dj-media-player-rental.jpg")
EquipmentModel.create(equipment_type_id: 4, name: 'QSC K8.2', description:'8-inch Active 2000W', image: "https://cdn1.bigcommerce.com/server4700/d8d4f/product_images/uploaded_images/qsc-k-8-2-rental-8-inch-speakers.jpg" )
EquipmentModel.create(equipment_type_id: 4, name: 'EV ETX Speaker', description: '15-inch Active 2000W', image: "https://cdn1.bigcommerce.com/server4700/d8d4f/product_images/uploaded_images/15-inch-ev-etx-speaker-rental.jpg" )
EquipmentModel.create(equipment_type_id: 4, name: 'JBL SRX 815P', description: '15-inch Active 2000W', image: "https://cdn1.bigcommerce.com/server4700/d8d4f/product_images/uploaded_images/jbl-srx-815p-loudspeaker-rental.jpg")
EquipmentModel.create(equipment_type_id: 5, name: 'QSC KW181', description: '18-inch Active 1000W', image: "https://cdn1.bigcommerce.com/server4700/d8d4f/product_images/uploaded_images/qsc-kw181-rental-subwoofer.jpg" )
EquipmentModel.create(equipment_type_id: 5, name: 'QSC KS212C', description: 'Dual 12-inch Cardioid Active 3600W', image: "https://cdn1.bigcommerce.com/server4700/d8d4f/product_images/uploaded_images/qsc-ks-212c-cardioid-subwoofer-rental.jpg")
EquipmentModel.create(equipment_type_id: 5, name: 'JBL SRX 828SP', description: 'Dual 18-inch Active 2000W', image: "https://cdn1.bigcommerce.com/server4700/d8d4f/product_images/uploaded_images/srx-828sp-jbl-subwoofer-rental.jpg")


OwnedEquipment.create(owner_id: 2, model_id: 1)
OwnedEquipment.create(owner_id: 2, model_id: 2)
OwnedEquipment.create(owner_id: 2, model_id: 3)
OwnedEquipment.create(owner_id: 2, model_id: 4)
OwnedEquipment.create(owner_id: 2, model_id: 5)
OwnedEquipment.create(owner_id: 2, model_id: 5)
OwnedEquipment.create(owner_id: 2, model_id: 6)
OwnedEquipment.create(owner_id: 2, model_id: 6)
OwnedEquipment.create(owner_id: 2, model_id: 7)
OwnedEquipment.create(owner_id: 2, model_id: 7)
OwnedEquipment.create(owner_id: 2, model_id: 10)
OwnedEquipment.create(owner_id: 2, model_id: 10)
OwnedEquipment.create(owner_id: 2, model_id: 12)
OwnedEquipment.create(owner_id: 2, model_id: 12)
OwnedEquipment.create(owner_id: 2, model_id: 13)

OwnedEquipment.create(owner_id: 3, model_id: 1)
OwnedEquipment.create(owner_id: 3, model_id: 2)
OwnedEquipment.create(owner_id: 3, model_id: 3)
OwnedEquipment.create(owner_id: 3, model_id: 4)
OwnedEquipment.create(owner_id: 3, model_id: 5)
OwnedEquipment.create(owner_id: 3, model_id: 5)
OwnedEquipment.create(owner_id: 3, model_id: 6)
OwnedEquipment.create(owner_id: 3, model_id: 6)
OwnedEquipment.create(owner_id: 3, model_id: 8)
OwnedEquipment.create(owner_id: 3, model_id: 8)
OwnedEquipment.create(owner_id: 3, model_id: 9)
OwnedEquipment.create(owner_id: 3, model_id: 9)
OwnedEquipment.create(owner_id: 3, model_id: 10)
OwnedEquipment.create(owner_id: 3, model_id: 10)
OwnedEquipment.create(owner_id: 3, model_id: 11)
OwnedEquipment.create(owner_id: 3, model_id: 11)
OwnedEquipment.create(owner_id: 3, model_id: 15)